### ISSUE TITLE
[Feature request] Multiple base Palindromes

### ISSUE THREAD

**Issue by tobozo** [jarun/primepalindrome#1]
Like decimal 719848917, which is 101010111010000000010111010101 in binary and 5272002725 in octal.

[Source](http://www.exploringbinary.com/finding-numbers-that-are-palindromic-in-multiple-bases/)

**Comment by jarun** [comment]
Please send in a patch.

**Comment by tobozo** [comment]
Not sure my C level would be enough to achieve that, but thanks for the spell check :-)

**Comment by jarun** [comment]
No problem! I do not have the bandwidth to try it out as of now.
